### ISSUE TITLE
Problem with replacements of push

### ISSUE THREAD

**Issue by yogicxl** [blockforest/stagexl-converter-pubrun#1]
the Regex rules replace every push string or subtring with .add.
For example:

String s = "pushing var to top of stack"; => String s = .adding var to top of stack";

please rectify this.

**Comment by nilsdoehring** [comment]
Thanks for your report! 

I fixed the issue in the pub global version of [Röckdöt Converter](https://github.com/blockforest/stagexl-converter-pubglobal), which is the only version I maintain.

This reminds me that I should have updated this project's readme a long time ago :-)
